name: CI for UB Image Converter API

on:
  pull_request:

jobs:
  test_code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Prepare the environment
        run: make deps devs

      - name: Test the code
        run: make test
